-- Assistente Mibro Brasil em observação. Aditiva e idempotente.
-- Trazido do workspace visual-fixes-work (mesmo id "mibro-assistant-observer",
-- mesma personalidade/Knowledge/intents da migration original
-- 20260909120000_mibro_assistant_observer) para existir UM único Assistente
-- Mibro em toda a base — se aquele workspace for mesclado depois, os
-- ON CONFLICT DO NOTHING abaixo (mesmos IDs) evitam duplicação. Não trazido
-- aqui de propósito: menu guiado/BotResponseBlock/BotSynonymGroup/
-- sectorIntake (migrations 20260911150000 em diante) — dependem de schema/
-- código que ainda não existe nesta árvore e são um recorte de feature
-- separado da integração de IA local (LOCAL_QWEN).
INSERT INTO "Bot" ("id","name","description","status","type","isSystem","channel","initialMessage","outsideHoursMessage","fallbackMessage","runOnNewConversation","runAfterReopen","autoReplyEnabled","toolsEnabled","ratingEnabled","featureFlags","updatedAt") VALUES ('mibro-assistant-observer','Assistente Mibro Brasil','Primeiro atendimento pós-triagem. Em observação: analisa e sugere, sem enviar mensagens.','ACTIVE','STANDARD',false,'META','Entendi. Consigo te ajudar com isso.','Recebi sua mensagem. Vou registrar as informações para nossa equipe continuar no próximo período.','Não encontrei informação oficial suficiente. Para não passar algo incorreto, vou encaminhar sua dúvida.',false,true,false,false,false,'{"interpretationEnabled":true,"conversationalBehaviorEnabled":true,"contextEnabled":true,"observationEnabled":true,"learningEnabled":true,"agentSuggestionsEnabled":true,"knowledgeSuggestionsEnabled":true,"knowledgeBaseEnabled":true,"handoffAutoPauseEnabled":true,"autoFinalizeOnResolution":false,"externalAiFallbackEnabled":false,"agentPlannerEnabled":true}'::jsonb,NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotPersonality" ("id","botId","preset","assistantName","roleDescription","tone","responseStyle","mandatoryBehaviors","forbiddenBehaviors","additionalInstructions","responseLength","updatedAt") VALUES ('mibro-assistant-personality','mibro-assistant-observer','PERSONALIZADO','Assistente Mibro Brasil','Assistente oficial de primeiro atendimento pós-triagem. Resolve dúvidas simples e intermediárias e encaminha quando um humano é necessário.',ARRAY['humano','educado','natural','moderno','tecnológico','confiável'],ARRAY['objetivo','prestativo','passo a passo','conciso'],ARRAY['Interpretar erros, abreviações e contexto','Perguntar só o necessário','Consultar Knowledge oficial','Dar uma orientação por vez','Confirmar o resultado','Resumir fatos e tentativas no handoff'],ARRAY['Inventar especificações, preço ou estoque','Repetir perguntas e procedimentos','Aprovar garantia, troca ou reembolso','Dar diagnóstico médico','Orientar reparo interno'],'Interprete significado, erros, abreviações, respostas curtas e contexto anterior. Mantenha modelo, app, celular/SO, problema, sintomas, objetivo, informações fornecidas, tentativas, falhas, resultado, pedido, canal de compra e assunto; nunca repita pergunta ou procedimento já respondido. Hierarquia: ferramenta oficial ao vivo > Knowledge oficial > contexto confirmado > regras do Bot > conhecimento geral. Confirme o modelo antes de afirmar GPS/GNSS, NFC, chamadas, música, água, sensores, bateria, tela, AOD, bússola ou compatibilidade. Preço, promoção, estoque e prazo promocional só ao vivo; sem acesso, indique a loja oficial. No Mibro Fit, diagnostique passo a passo e dê uma orientação por vez: energia/carga, Bluetooth, permissões, pareamento pelo app, vínculo anterior e reinício quando apropriado; chamadas podem exigir áudio adicional, sem confundir com pareamento principal. Problema físico, defeito, água, superaquecimento, falha persistente, reparo ou garantia: explique brevemente, não desmonte nem prometa cobertura e encaminhe ao Suporte. Pedido, pagamento, entrega, troca, devolução e nota fiscal: use ferramenta oficial se disponível ou Atendimento; nunca finja consulta nem autorize resultado. Compra/comparação: entenda a necessidade e use apenas especificações confirmadas. Revenda/parceria: Parcerias. Bem-estar não é diagnóstico médico. Primeiro ajude e depois ofereça link oficial. Faça perguntas apenas quando necessárias. Após orientação relevante, confirme se funcionou; positivo resolve, negativo atualiza o caso. No handoff, preserve setor, motivo, produto, problema, informações, procedimentos, resultado e pendência.','SHORT',NOW()) ON CONFLICT ("botId") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-garantia','mibro-assistant-observer','Garantia Mibro Brasil','WARRANTY','https://mibrobrasil.com.br/pages/termos-de-garantia','Nunca aprovar cobertura, troca ou reembolso automaticamente. Casos de defeito dependem de análise humana.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-catalogo','mibro-assistant-observer','Catálogo oficial','PRODUCT','https://mibrobrasil.com.br/collections/todos-os-produtos','Preço, promoção e estoque são dinâmicos; consultar a fonte atual ou orientar a loja oficial.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-app','mibro-assistant-observer','Mibro Fit','MANUAL','https://mibrobrasil.com.br/pages/app-mibro','Pareamento principal pelo Mibro Fit. Requisitos publicados: Android 5.0+ com Bluetooth 4.0; iOS 13.0+.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-trocas','mibro-assistant-observer','Trocas e devoluções','POLICY','https://mibrobrasil.com.br/policies/refund-policy','Direito de arrependimento em até 7 dias corridos após o recebimento, conforme condições e solicitação prévia. Nunca autorizar automaticamente.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-entrega','mibro-assistant-observer','Entrega','POLICY','https://mibrobrasil.com.br/policies/shipping-policy','Situação específica exige ferramenta oficial; sem ferramenta, encaminhar ao Atendimento.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-privacidade','mibro-assistant-observer','Privacidade','POLICY','https://mibrobrasil.com.br/policies/privacy-policy','Política oficial de privacidade.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-termos','mibro-assistant-observer','Termos','POLICY','https://mibrobrasil.com.br/policies/terms-of-service','Compatibilidade e funções variam por modelo, sistema e versão.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-sobre','mibro-assistant-observer','Sobre a Mibro','GENERAL','https://mibrobrasil.com.br/pages/sobre-nos','Página institucional oficial.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-contato','mibro-assistant-observer','Contato','GENERAL','https://mibrobrasil.com.br/policies/contact-information','Canais oficiais de contato.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-legal','mibro-assistant-observer','Aviso legal','POLICY','https://mibrobrasil.com.br/policies/legal-notice','Aviso legal oficial.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-c4','mibro-assistant-observer','mibro-c4','PRODUCT','https://mibrobrasil.com.br/products/mibro-c4','Tela TFT 2,01 pol. 240x296; chamadas Bluetooth, controle e reprodução de música; mais de 100 modos; 2 ATM; Bluetooth 5.3; autonomia publicada de até 10 dias no uso diário e 45 no básico.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-a3','mibro-assistant-observer','mibro-a3','PRODUCT','https://mibrobrasil.com.br/products/mibro-a3','Fonte oficial do modelo; confirmar nela cada especificação antes de responder.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-lite-3','mibro-assistant-observer','mibro-lite-3','PRODUCT','https://mibrobrasil.com.br/products/mibro-lite-3','Tela AMOLED 1,3 pol. 360x360 com AOD; GPS/BeiDou/GLONASS/Galileo/QZSS; chamadas e reprodução de música; mais de 100 modos; 2 ATM; Bluetooth 5.3; até 12 dias no uso diário.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-lite-3-pro','mibro-assistant-observer','mibro-lite-3-pro','PRODUCT','https://mibrobrasil.com.br/products/mibro-lite-3-pro','Tela AMOLED 1,32 pol.; GNSS com GPS/BeiDou/GLONASS/Galileo/QZSS; NFC e chamadas Bluetooth; mais de 150 modos; 5 ATM; até 15 dias no uso diário e 15 horas em GPS.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-gs-pro-2','mibro-assistant-observer','mibro-gs-pro-2','PRODUCT','https://mibrobrasil.com.br/products/mibro-gs-pro-2','Mais de 150 modalidades e triatlo; rotas GPX/KML/TCX; GNSS de dupla frequência GPS L1+L5; chamadas Bluetooth; Mibro OS 2.0; 5 ATM; até 20 dias de uso diário e 20 horas de GPS.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-gs-pro','mibro-assistant-observer','mibro-gs-pro','PRODUCT','https://mibrobrasil.com.br/products/mibro-gs-pro','Tela AMOLED 1,43 pol.; GPS/BeiDou/GLONASS/Galileo/QZSS; NFC e chamadas Bluetooth; 105 modos; 5 ATM; até 20 dias de uso diário, 17 horas de GPS e 11 horas de chamadas.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-gs-active','mibro-assistant-observer','mibro-gs-active','PRODUCT','https://mibrobrasil.com.br/products/mibro-gs-active','Tela AMOLED de 1000 nits; GPS/BeiDou/GLONASS/Galileo/QZSS; 150 modos; 5 ATM; até 20 dias no modo diário, 50 no básico e 15 horas no GPS.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "KnowledgeSource" ("id","botId","title","type","source","content","tags","updatedAt") VALUES ('mibro-produto-mibro-gs-active2','mibro-assistant-observer','mibro-gs-active2','PRODUCT','https://mibrobrasil.com.br/products/mibro-gs-active2','Tela AMOLED 466x466 de 1200 nits; GPS de dupla frequência L1+L5; chamadas Bluetooth; mais de 150 modos; 5 ATM; até 20 dias de uso diário e 15 horas de GPS; sincronização com Strava, Apple Health e Google Fit.',ARRAY['mibro','oficial'],NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-1','mibro-assistant-observer','Conexão e pareamento','Conexão e pareamento',100,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='SUPORTE'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-1-example-1','mibro-assistant-intent-1','relogio n conecta') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-1-example-2','mibro-assistant-intent-1','app n acha') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-1-example-3','mibro-assistant-intent-1','n pareia') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-1-example-4','mibro-assistant-intent-1','bluetooh nao pega') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-1-example-5','mibro-assistant-intent-1','fica procurando e nada') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-2','mibro-assistant-observer','Aplicativo e notificações','Aplicativo e notificações',99,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='SUPORTE'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-2-example-1','mibro-assistant-intent-2','nao chega notificacao') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-2-example-2','mibro-assistant-intent-2','mibro fit nao sincroniza') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-2-example-3','mibro-assistant-intent-2','app nao atualiza') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-3','mibro-assistant-observer','Carregamento e bateria','Carregamento e bateria',98,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='SUPORTE'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-3-example-1','mibro-assistant-intent-3','relogio nao carrega') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-3-example-2','mibro-assistant-intent-3','bateria acaba rapido') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-3-example-3','mibro-assistant-intent-3','nao liga depois de carregar') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-4','mibro-assistant-observer','Funções e especificações','Funções e especificações',97,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='SUPORTE'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-4-example-1','mibro-assistant-intent-4','ele tem gps') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-4-example-2','mibro-assistant-intent-4','pode nadar') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-4-example-3','mibro-assistant-intent-4','tem nfc') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-4-example-4','mibro-assistant-intent-4','faz ligacao') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-5','mibro-assistant-observer','Garantia e defeito','Garantia e defeito',96,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='SUPORTE'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-5-example-1','mibro-assistant-intent-5','quero acionar garantia') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-5-example-2','mibro-assistant-intent-5','tela quebrou') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-5-example-3','mibro-assistant-intent-5','entrou agua') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-5-example-4','mibro-assistant-intent-5','precisa de assistencia') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-6','mibro-assistant-observer','Pedidos e entrega','Pedidos e entrega',95,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='ATENDIMENTO'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-6-example-1','mibro-assistant-intent-6','onde esta meu pedido') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-6-example-2','mibro-assistant-intent-6','pedido atrasado') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-6-example-3','mibro-assistant-intent-6','preciso da nota fiscal') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-7','mibro-assistant-observer','Troca e devolução','Troca e devolução',94,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='ATENDIMENTO'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-7-example-1','mibro-assistant-intent-7','quero devolver') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-7-example-2','mibro-assistant-intent-7','quero trocar') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-7-example-3','mibro-assistant-intent-7','pedido reembolso') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-8','mibro-assistant-observer','Escolha de produto','Escolha de produto',93,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='COMERCIAL'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-8-example-1','mibro-assistant-intent-8','qual mibro comprar') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-8-example-2','mibro-assistant-intent-8','qual modelo e melhor') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-8-example-3','mibro-assistant-intent-8','tem em estoque') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-8-example-4','mibro-assistant-intent-8','quanto custa') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntent" ("id","botId","name","description","priority","active","fallbackAction","categoryId","updatedAt") VALUES ('mibro-assistant-intent-9','mibro-assistant-observer','Parceria e revenda','Parceria e revenda',92,true,'TRANSFER_TO_CATEGORY',(SELECT "id" FROM "Category" WHERE "code"='PARCERIAS'),NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-9-example-1','mibro-assistant-intent-9','quero ser revendedor') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-9-example-2','mibro-assistant-intent-9','comprar atacado') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "BotIntentExample" ("id","intentId","text") VALUES ('mibro-assistant-intent-9-example-3','mibro-assistant-intent-9','sou influenciador') ON CONFLICT ("id") DO NOTHING;
