-- A Zenvia permanece no enum somente para preservar registros históricos,
-- mas deixa de ser aceita e exibida na configuração de novos Bots.
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'INSTAGRAM_DIRECT';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'INSTAGRAM_COMMENTS';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'FACEBOOK_MESSENGER';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'FACEBOOK_COMMENTS';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'MERCADO_LIVRE';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'TIKTOK_SHOP';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'AMAZON_MARKETPLACE';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'SHOPEE';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'SHEIN_MARKETPLACE';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'GOOGLE_REVIEWS';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'RECLAME_AQUI';
